### ISSUE TITLE
SELECT cdb_cartodbfytable('foo') returns "unknown(2278)"

### ISSUE THREAD

**Issue by javisantana** [CartoDB/CartoDB-SQL-API#192]
using a valid api_key, it should return something more descriptive

**Comment by rochoa** [comment]
cc @pramsey as he was working on a newer version of `CDB_CartodbfyTable `.

**Comment by pramsey** [comment]
what was it about this particular 'foo' that made it toss the error?

**Comment by rochoa** [comment]
It's not an error but we were wondering if CDB_CartodbfyTable should return something different than void: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L613-L614

**Comment by pramsey** [comment]
It's kind of a mixed bag ATM, basically throwing an exception if things go wrong. Returning a boolean would imply maybe trapping all the exceptions and returning false up the stack instead. But any failure to do that and the calling code would still have to handle the exceptions. Not sure that a boolean return would actually be any more informative: it works, or it fails and you get an exception about why.

**Comment by rochoa** [comment]
OK, fair enough.

I cc'ed you just in case you had an alternative but I agree it's ok as far
as we get an exception if it fails.

On Tue, May 12, 2015 at 3:14 PM, Paul Ramsey <notifications@github.com>
wrote:

> It's kind of a mixed bag ATM, basically throwing an exception if things go
> wrong. Returning a boolean would imply maybe trapping all the exceptions
> and returning false up the stack instead. But any failure to do that and
> the calling code would still have to handle the exceptions. Not sure that a
> boolean return would actually be any more informative: it works, or it
> fails and you get an exception about why.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/CartoDB-SQL-API/issues/192#issuecomment-101270619>
> .
>



-- 
Raul Ochoa
rochoa@cartodb.com

**Comment by rochoa** [comment]
This was addressed in https://github.com/CartoDB/node-cartodb-psql/pull/8
