### ISSUE TITLE
batch endpoint

### ISSUE THREAD

**Issue by javisantana** [CartoDB/CartoDB-SQL-API#218]
Sometimes you need to execute a long running query, for example for a analysis, index creation and so on. In those cases the current endpoint fails due timeouts in http layers.

My proposal is to add a new endpoint like

```
/api/v1/sql_batch?q=update ....
```

if will return a ``job_id`` like

```
{ job_id: 12345 }
```

so the user can check the state

```
/api/v1/sql?q=select state from cdb_jobs where job_id = '....'
```

The management would work using the table, for example, cancelling a job:

```
/api/v1/sql?q=delete from cdb_jobs where job_id = '....'
```

cc @pramsey @rochoa

**Comment by danicarrion** [comment]
+1

2015-05-07 14:16 GMT+02:00 javi santana <notifications@github.com>:

> Sometimes you need to execute a long running query, for example for a
> analysis, index creation and so on. In those cases the current endpoint
> fails due timeouts in http layers.
>
> My proposal is to add a new endpoint like
>
> /api/v1/sql_batch?q=update ....
>
> if will return a job_id like
>
> { job_id: 12345 }
>
> so the user can check the state
>
> /api/v1/sql?q=select * from cdb_jobs where job_id = '....'
>
> cc @pramsey <https://github.com/pramsey> @rochoa
> <https://github.com/rochoa>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/CartoDB-SQL-API/issues/218>.
>



-- 
Daniel Carrión
daniel@cartodb.com

**Comment by pramsey** [comment]
so the queue is going to be spread out over every single account in the system? (one cdb_jobs table in each account) this seem potentially awful

**Comment by javisantana** [comment]
my approach here is not to think in how cartodb works but how I would implement this in postgres. We already have a system like that (the cache).

In any case, the approach having a single queue would be to make sql_batch a rest endpoint to get/list/update/remove jobs 

What would be your approach?

**Comment by rochoa** [comment]
That keeps me wondering things:
 - What information does "job_id" encapsulate? Postgres' query PID?
 - Where is it saved? Postgresql itself (I guess that from `select state from cdb_jobs...`) ?
 - How do we ensure isolation between users? So if I run a long query and I try to cancel it, it doesn't cancel other users queries?

Those questions are for me also! :dancer:

**Comment by javisantana** [comment]
another desirable thing: provide a way to fetch results for big exports so the results can be obtained somewhow. Also for big outputs obviously

**Comment by dgaubert** [comment]
Then user must know when a query is a long running query, right?. Or should SQL-API find it out?

**Comment by pramsey** [comment]
Yes, the expectation is that they'd know the query is long.

**Comment by javisantana** [comment]
@dgaubert I think we can close this, right?

**Comment by dgaubert** [comment]
We are about to close it, waiting for the PR, coming soon!
