### ISSUE TITLE
SQL COMMENT not working properly

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/CartoDB-SQL-API#235]
'COMMENT ON TABLE chriswhong.nytracts IS 'NY State Census Tracts''

results in 'syntax error at or near "ON"'

**Comment by pramsey** [comment]
Is this SQL API or in the Editor?

**Comment by chriswhong** [comment]
In the editor

**Comment by pramsey** [comment]
File in https://github.com/CartoDB/cartodb

**Comment by zenitraM** [comment]
Works on the SQL API

**Comment by chriswhong** [comment]
Is an Editor validation problem, not a SQL API problem.  Closing.
