### ISSUE TITLE
select * from empty_table can fail through sql api

### ISSUE THREAD

**Issue by rafatower** [CartoDB/CartoDB-SQL-API#245]
I usually execute stuff like this for testing:
```
tests=# create table test_ghost_tables();
CREATE TABLE
tests=# select * from test_ghost_tables;
--
(0 rows)
```
(table without rows and **without columns**)

but when executing the select through the sql api:
```
{"error":["syntax error at or near \"from\""]}
```

I'm worried I'm still getting the same error after adding some dummy column:
```
alter table test_ghost_tables add column id integer not null
```

I'm pretty sure that used to work before. cc/ @rochoa

**Comment by rafatower** [comment]
It has to do with the table name. This fixes it:
```
alter table test_ghost_table rename to test_gt
select * from test_gt
```

sorry about the noise

**Comment by rafatower** [comment]
Works directly with the api, it fails when wrapping through the editor's sql panel, will refine this bug description and create in appropriate repo.

**Comment by rochoa** [comment]
Just to have a bit more of context: from a query like `select * from test_ghost_tables` the editor ends doing a query like `select  from (select * from test_ghost_tables) __wrapped`, due the lack of columns in test_ghost_tables table.
