### ISSUE TITLE
Bug: Comments in Editor SQL pane can make correct queries error

### ISSUE THREAD

**Issue by javitonino** [CartoDB/CartoDB-SQL-API#274]
@andrewbt commented on [Thu Jan 07 2016](https://github.com/CartoDB/cartodb/issues/6366)

I was commenting out things and using the SQL pane as a "scratchpad", but was getting errors when I tried to run the query and couldn't figure out what was going wrong. Until I got rid of all the comments, then it worked fine.

Original query with comments at the top (including newlines):

```
-- (MedianState1 * NumberofSalesState1 + MedianState2*NumberofSalesState2 + ... MedianState50*NumberofSalesState50)/TotoalNumberOfSales
-- sum(tinc.totalinc)/totpop.sumhouse as combomedian
--with tinc as (SELECT cartodb_id, (hhi * households) as totalinc FROM athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3), totpop as (select sum(households) as sumhouse from athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3)
--select totpop.sumhouse
select tinc.totalinc, totpop.sumhouse from (SELECT cartodb_id, (hhi * households) as totalinc FROM athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) tinc, (select sum(households) as sumhouse from athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) totpop
```

Query that works fine (the functional non comment part) when run by itself:

```
select tinc.totalinc, totpop.sumhouse from (SELECT cartodb_id, (hhi * households) as totalinc FROM athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) tinc, (select sum(households) as sumhouse from athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) totpop
```

---

@andrewbt commented on [Thu Jan 07 2016](https://github.com/CartoDB/cartodb/issues/6366#issuecomment-169803328)

interestingly though, this query with just one comment also works correctly without erroring:

```
-- (MedianState1 * NumberofSalesState1 + MedianState2*NumberofSalesState2 + ... MedianState50*NumberofSalesState50)/TotoalNumberOfSales
select tinc.totalinc, totpop.sumhouse from (SELECT cartodb_id, (hhi * households) as totalinc FROM athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) tinc, (select sum(households) as sumhouse from athompson.censustract_1 where cartodb_id = 1 or cartodb_id = 2 or cartodb_id = 3) totpop
```

**Comment by javitonino** [comment]
@andrewbt Moved to SQL-API

It appears the problem happens when an even number of comment lines are added. With an odd number of commented lines, it works. The query doesn't matter, the error can be replicated with:

```SQL--
--
--
SELECT 1
```
This generates the following SQL API call that fails:
> GET /api/v2/sql?rows_per_page=40&page=0&sort_order=asc&order_by=&filter_column=&filter_value=&sql_source=null&api_key=02120bdc9b1b5065ce678c8b3363b0f57d6f19bd&q=select%20%22%3Fcolumn%3F%22%20from%20(--%0A--%0ASELECT%201)%20__wrapped

The same query works when run directly in psql console.

**Comment by javisantana** [comment]
could you take care @javitonino ?

**Comment by rochoa** [comment]
This is not close until we upgrade the dependency.

**Comment by javitonino** [comment]
This was merged a long time ago, closing :tada:
