### ISSUE TITLE
Support Infinity/-Infinity

### ISSUE THREAD

**Issue by jsanz** [CartoDB/CartoDB-SQL-API#303]
The float and double precision types support `Infinity` and `-Infinity` special values, but the SQL API retrieves a `Null` value on a table with those values.

To test this I've created a table directly from the `psql` console:

![2016-05-18_18 58 10_selection](https://cloud.githubusercontent.com/assets/188264/15367729/9c4d5596-1d2a-11e6-9ce8-16ab8f54f288.png)

But then when retrieving that row using the SQL API the row has two `null` values.

Would it be possible to support them?

**Comment by rochoa** [comment]
What do you expect as output?

JSON cannot represent Infinity/-Infinity/NaN.

If you try other format like csv you will get Infinity/-Infinity as strings.

**Comment by jsanz** [comment]
OK so this is just a limitation of JSON. Actually I tried an `INSERT` from SQL API and works, it's just the JSON output then. I'll close the ticket as for now and reopen if I find a sensible answer :smile:
