### ISSUE TITLE
Use Redis multi command to retrieve several batch jobs

### ISSUE THREAD

**Issue by rochoa** [CartoDB/CartoDB-SQL-API#351]
In Job Backend [we use a queue when we want to retrieve several jobs](https://github.com/CartoDB/CartoDB-SQL-API/blob/01d1866e1140ce0a4034167016341863c96de4a6/batch/job_backend.js#L208-L226), what about using redis' Multi command?

By the way, [cartodb-redis library has support for it](https://github.com/CartoDB/node-cartodb-redis/blob/44f3a77d35fd4f27b6a9a91d7ebabe007d783a02/lib/carto_metadata.js#L141-L145).

**Comment by dgaubert** [comment]
To retrieve a job list, we are doing:
 - Get  a list of `job_id`s from `userIndexer.list`
 - For each `job_id`: 
   - if exists (ttl has not expired) return the job.
   - if not exists (ttl has expired) remove `job_id` from user index.

Not sure how redis' Multi-command could fit here, we need to keep user index updated (TTL).

BTW. I'm not happy keeping a user index of elements that has a TTL and are removed automatically. Also, I'm not sure about the usability of listing all user's jobs, but it's too late to drop it. 

I would like to have a mechanism to expire elements of a list in redis. Or bind elements in redis to expire one when another expires.

Any clues?

**Comment by rochoa** [comment]
By requesting a batch of jobs, via multi command, you can follow the same strategy, removing from the user list the ones that didn't return from the multi command. And then you can do another multi command to remove all expired jobs ids from the user list.

**Comment by dgaubert** [comment]
But have in mind that multi command could reach thousands of commands. Is it going to work w/o issues?

Anyway, I'd like to think another way to do that or, simply, to remove that feature (list all jobs of a user)

**Comment by dgaubert** [comment]
Since we removed that feature... closing
