### ISSUE TITLE
Add Golang client to libraries list?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/CartoDB-SQL-API#388]
hi @rochoa should i assign elsewhere?
cc @csobier 

In our SQL API docs we have a section on [libraries in different languages](https://carto.com/docs/carto-engine/sql-api/libraries-support/#libraries-in-different-languages).

S/B client is requesting we add [CARTO client for Golang](https://github.com/agonzalezro/cartodb_go). 

Do we want to add? Or need me to ask for more details?

**Comment by rochoa** [comment]
Feel free to open a PR.

However, we should state clearly that all those libraries are externally developed and maintained.

**Comment by ztephm** [comment]
Thanks! 

Hi @csobier I can make the PR but which path is the proper 07-libraries-support.md in? I only see one listing the libraries out in the old version of repo.

**Comment by csobier** [comment]
This is the path:  https://github.com/CartoDB/CartoDB-SQL-API/blob/master/doc/libraries_support.md

Thanks! And you can tag me to review, I'll make sure the note about using external libraries is strong. It's a separate step to pull the changes into the Docs repo.
