### ISSUE TITLE
Remove in-memory tableCache and related code

### ISSUE THREAD

**Issue by rafatower** [CartoDB/CartoDB-SQL-API#424]
The `tableCache` is now disabled by default. See https://github.com/CartoDB/CartoDB-SQL-API/issues/422

This issue is just a follow up not to forget about removing all the related code.

cc/ @rochoa for prioritization

**Comment by rafatower** [comment]
@dgaubert @CartoDB/dc-managers this is a leftover from the past. The in-memory `tableCache` has been disabled for ~ 2 years and can be removed now.

**Comment by dgaubert** [comment]
WIP #605

**Comment by dgaubert** [comment]
and https://github.com/CartoDB/cartodb-platform/pull/5825

**Comment by dgaubert** [comment]
Done
