### ISSUE TITLE
Gather information about default values

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/CartoDB-SQL-API#440]
The project about SQL API limits (https://github.com/CartoDB/cartodb-management/issues/4976) wants to set limits according to the real use of the API. Current default values for execution times are not working well, and service's reliability is being affected by that.

First, we need to know the default values for queries execution time both on public and private data.

**Comment by oleurud** [comment]
Timeout for user queries: 300 seconds
Timeout for public queries: 25 seconds
