### ISSUE TITLE
Gather use statistics of query execution times

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/CartoDB-SQL-API#441]
The project about SQL API limits (CartoDB/cartodb-management#4976) wants to set limits according to the real use of the API. New limits must be based on real use, to gain reliability and user experience at the same time.

We need to understand what's happening in fact with the SQL API. So we need to gather statistics with these key points:

- For the last 40 days
- For every type of account
- Organized by percentiles and its time in milliseconds.

The goal is to understand easily how many users are on the percentile x for n milliseconds. With that kind of information, we can take better decisions choosing the new limits.

**Comment by inigomedina** [comment]
This is one issue with statistics information from @msaenzde11: CartoDB/cartodb-platform#3266

**Comment by inigomedina** [comment]
We got some statistics from the issue mentioned above, @msaenzde11. It's one elaborated by you. Did you remember if those statistics were useful? If at the end of the project were taken as valid and thus used?

**Comment by inigomedina** [comment]
cc @msaenzde11

**Comment by inigomedina** [comment]
All the information regarding statistics from @msaenzde11 has been given on #442

**Comment by inigomedina** [comment]
The first Kibana Dashboards for slow queries and queries times execution made by @oleurud.
http://kibana.cartodb.net/#/dashboard/elasticsearch/Slow%20queries
http://kibana.cartodb.net/#/dashboard/elasticsearch/Queries%20duration

**Comment by oleurud** [comment]
Do we need this issue? All the info related is in #442 Or maybe I am losing something
