### ISSUE TITLE
Gather statistics about render times

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/CartoDB-SQL-API#442]
The project about SQL API limits (CartoDB/cartodb-management#4976) wants to set limits according to the real use of the API. New limits must be based on real use, to gain reliability and user experience at the same time.

Since SQL API calls mean render actions too, we need to measure those render actions as well. So we need to gather statistics with these key points:

- For the last 40 days
- For every type of account
- Organized by percentiles and its time in milliseconds.

The goal is to understand easily how many users are on the percentile x for n milliseconds. With that kind of information, we can take better decisions choosing the new limits.

**Comment by inigomedina** [comment]
This is one issue with statistics information from @msaenzde11: https://github.com/CartoDB/cartodb-platform/issues/3266

**Comment by inigomedina** [comment]
We got some statistics from the issue mentioned above, @msaenzde11. It's one elaborated by you. Did you remember if those statistics were useful? If at the end of the project were taken as valid and thus used?

**Comment by msaenzde11** [comment]
@inigomedina @oleurud These statistics were extracted for a 1 week period due to the amount of logs that we constantly generate for the goal of recognizing the amount of users (at each segment) that would be affected after some limits applied to their accounts. I was asuming they had been useful, but don't believe they were applied... It'd be better @rochoa to know it!

**Comment by inigomedina** [comment]
Thanks, @msaenzde11. Do we have any kind of dashboard for that? Is there maybe on Kibana a kind of search with filters to gather now these data? Or it was just a script launched at that time?

And, do we have aggregated data? On the issue mentioned above, I see the results for a month period of time, divided into different rows with the numbers for each type of account. But not as an aggregated information.

**Comment by msaenzde11** [comment]
Hey @inigomedina, it's true, at the end I managed to extract data for one month (I didn't remember, as we talked a lot to do it for a week). Unfortunately it was a script launched at that time.

Regarding aggregated data, which kind of results would you like? Do you mean total percentiles (not caring about account_types), don't you? If this is the case, I believe I still have the raw data, so I can try to provide you with this nrs :)

**Comment by inigomedina** [comment]
Well, I think data are distributed daily. They are too distributed in percentiles with ranges that don´t allow to understand types of groups.

To me, it would be much easier to create groups of response times. So you can say: "25% of all of the response times are under 5 seconds", "20% of all of the response times are above 5 seconds and under 10 seconds", etc.

**Comment by oleurud** [comment]
**Logs**
We will need to read the Postgres logs for the stats gathering. Currently, the Postgres logs are saving the queries with a time duration of more than 2 seconds. If we can to suppose that the limits will be upper than 2 seconds, we can work without changing the database logs. If we can not suppose it, we need to change the database logs from some days and wait some time until the logs have data. Also, this second way increases the time needed for the stats gathering (there will be more stats for processing).

Another important thing, the logs do not save info about the account type.

**Source of data**
We have 2 options to extract the data:
- From Kibana (it reads the Postgres logs)
- Straight from Postgres logs

We have code for both cases (a good starting point). 

So, as we only need the execution time and who do the request, for me, it is easier to use Kibana. 

**For last 40 days**
It is too much stats. I don't know the log size by day (it depends on the query duration limit), but I expect several gigabytes. Can we use a small dataset? We can show it on the fly.

**Comment by inigomedina** [comment]
The first Kibana Dashboards for slow queries and queries times execution made by @oleurud.
http://kibana.cartodb.net/#/dashboard/elasticsearch/Slow%20queries
http://kibana.cartodb.net/#/dashboard/elasticsearch/Queries%20duration

**Comment by oleurud** [comment]
The "slow queries" is not made by me ;)

**Comment by oleurud** [comment]
Based on 4 millions of slow queries (queries with a duration of more than 2 seconds) from october 2nd to november 1st, we have the results:

|   Account  	|   p99   	|   p95  	|  p75  	|  p50  	|
|:----------:	|:-------:	|:------:	|:-----:	|:-----:	|
| Enterprise 	|  57.584 	| 18.432 	| 6.047 	| 2.762 	|
|    Free    	| 127.016 	| 24.659 	| 5.386 	| 2.746 	|
|  Personal  	| 100.126 	| 26.003 	| 8.652 	| 4.385 	|

**Comment by inigomedina** [comment]
Great @oleurud. That information is on the ranges we thought. With that numbers, we can start thinking about first date to apply them.
