### ISSUE TITLE
Activate limits for signups/free users

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/CartoDB-SQL-API#444]
The project about SQL API limits (CartoDB/cartodb-management#4976) wants to set limits according to the real use of the API, trying to avoid reliability issues.

After researching on real use and deciding new limits, it's time to implement them. Rules to do it are explained by @jgoizueta on the main issue, in which the roll-up is included.

Please, @rochoa, we need to set a date/time with you to activate the new limits.

**Comment by inigomedina** [comment]
I've been talking to @rochoa and @jorgesancha about a good date for starting with this. Everyone prefers to start in a conservative manner, even following the steps we created on the roll-up. So, let's start not with all the free users, but just with a part of them, and watch how they perform.

@oleurud How do you see it? Could we start with a number of free users (for instance, 25%)? We have ready the dashboard for watching the over limits responses, so after we activate those new limits for that set, we could watch how they perform and decide according to that whether we continue expanding the set to a bigger range.

**Comment by jorgesancha** [comment]
Hey one thing! Make sure you let Support know before you get started and let them know what the effects of hitting the limits would be for users (what they'll see, etc.)

**Comment by inigomedina** [comment]
Absolutely, @jorgesancha. Part of the roll-ups should include other teams (support, solutions, etc.) since the impact on users is mainly absorbed by them. Our provisional CARTO projects want to be a partial solution for that: working as a general dashboard not only thought for the engineering team.

**Comment by inigomedina** [comment]
A good approach might also be to exclude from this first step free users that have custom limits. Since they are exceptions, they could be "special" free users, and thus potential problems for the new limits.

Can we have that information? Is there any kind of another flag that allows us to find special free users?

cc @rochoa

**Comment by oleurud** [comment]
Roll out plan: https://github.com/CartoDB/cartodb-management/issues/4976#issuecomment-346358343
