### ISSUE TITLE
Test new SQL limits on staging

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/CartoDB-SQL-API#445]
The project about SQL API limits (CartoDB/cartodb-management#4976) wants to set limits according to the real use of the API. Once we have researched and found reasonable limits for real uses, we want to test them on staging. Solutions/support teams can provide useful information regarding typical cases like demos, free users learning, etc.

@oleurud I don't know if you can activate new limits on staging, or if we depend on other teams for doing that. I think @jsanz was thinking just in activating these on specific accounts, and load usual datasets/maps on them, to test it. So, it doesn't' mean activating for all free users/signups, etc., but specifically for the accounts @jsanz tells us.

**Comment by oleurud** [comment]
Ok. We need these specifics accounts to set them the new limits (Please, you send me these usernames by email).

How many seconds do you want that I set to the users to do the tests?

**Comment by inigomedina** [comment]
> How many seconds do you want that I set to the users to do the tests?

5 secs.

**Comment by oleurud** [comment]
All users in staging have a database timeout of 5 seconds
