### ISSUE TITLE
COPY feature code refactor

### ISSUE THREAD

**Issue by oleurud** [CartoDB/CartoDB-SQL-API#506]
COPY TO and FROM methods are doing a lot of things (one smell is that they receive many parameters). They encapsulate almost everything from the middleware, which is fine but I think that some things are better to handle in the middleware than here. Middlewares should be the ones responsible for req and res and we shouldn't pass them to collaborators.

It is not easy to solve due to the dependencies between Request/Response objects and `pgstream` (in the event of one has the other as a dependency)

This issue becomes from #480 code review (https://github.com/CartoDB/CartoDB-SQL-API/pull/480#discussion_r193092125)

**Comment by oleurud** [comment]
We are working on some branches at the same time. I will explain the situation.

The first version of the solution was: https://github.com/CartoDB/CartoDB-SQL-API/pull/503 And then, @dgaubert started https://github.com/CartoDB/CartoDB-SQL-API/pull/508 from the other.

From both refactor, we have learned some things and found some bugs. I have created https://github.com/CartoDB/CartoDB-SQL-API/pull/509 with them.

The final idea is to merge: master, #508 and #509

**Comment by rafatower** [comment]
Hey, just a small request :pray: : please do not mix refactors and bugfixes when possible. E.g: log rotation and reopening file streams. Why? because that way we do not block fairly small and safe bugfixes with potentially hard-to-review refactors. They can be reviewed, tested and deployed independently.

**Comment by oleurud** [comment]
Yes, you are totally right. It is my fault. I will try to improve it in the future

**Comment by rafatower** [comment]
Hahaha! nobody's fault, my friend. Just "good practices" that are easier to spot to an external observer :eyes: 

Thanks a lot for the effort put here. Hope you get the clarity and maintainability gains you're looking for in these refactors :slightly_smiling_face:

**Comment by oleurud** [comment]
#509 merged

**Comment by oleurud** [comment]
We have a PR improving the tests, in order to allow us to make a more confident refactor
https://github.com/CartoDB/CartoDB-SQL-API/pull/510

**Comment by oleurud** [comment]
The #510 is merged and deployed and the #508 is ready to CR.

**Comment by oleurud** [comment]
#508 deployed and all finished (for now)
