### ISSUE TITLE
Make sure tmpDir exists

### ISSUE THREAD

**Issue by enekid** [CartoDB/CartoDB-SQL-API#527]
Make sure the `tmpDir` exists when using the [OGR exporters](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/app/models/formats/ogr)

Comes from [[WRI] Intermittent error when accessing SQL API #1681](https://github.com/CartoDB/support/issues/1681)

**Comment by oleurud** [comment]
The PR ---> https://github.com/CartoDB/CartoDB-SQL-API/pull/536
