### ISSUE TITLE
copyfrom `Uncaught exception: Error: incorrect header check`

### ISSUE THREAD

**Issue by oleurud** [CartoDB/CartoDB-SQL-API#528]
If you request a gzipped copyfrom sending a bad formatted gzip body (at least, we think the cause is a bad formatted gzip body), the API crashes. In the log you can see: 
```
Uncaught exception: Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)
```

The error was reported by @rafatower who could add more info

**Comment by rafatower** [comment]
I started working on this, by adding a test for this case: https://github.com/CartoDB/CartoDB-SQL-API/pull/530

**Comment by rafatower** [comment]
Go for it! Monday works for me. Thanks a lot! :slightly_smiling_face:

**Comment by oleurud** [comment]
:rocket: in production
