### ISSUE TITLE
Add `Authorization` to supported CORS header

### ISSUE THREAD

**Issue by javitonino** [CartoDB/CartoDB-SQL-API#534]
We want to add the `Authorization` header to SQL API and Maps API supported CORS header so we can use this kind of authentication from frontend-only apps.

**Comment by Captain-Oski** [comment]
I back this request. 👍

**Comment by oleurud** [comment]
:rocket: https://github.com/CartoDB/Windshaft-cartodb/pull/1063 & https://github.com/CartoDB/CartoDB-SQL-API/pull/557
