### ISSUE TITLE
URL for carto on-premises version

### ISSUE THREAD

**Issue by ohnova** [CartoDB/CartoDB-SQL-API#539]
I've searched for url to access carto on-premises in a couple of days but I couldn't find it.
I found only cloud version url,  
`https://{username}.carto.com/api/v2/sql?q={SQL statement}&api_key={api_key}`

I configured CARTO_DOMAIN in carto-builder.config file that would be accessible like https://carto.com.
There should be more detailed documentation needed. 

Let me know how to access carto datasets with sql v2 api in On-Premises. Thank you in advance.

**Comment by dgaubert** [comment]
Hey!

This is the public repository. If you have issues with your on-premises configuration, please, contact to the support team directly: onpremise-support@carto.com
