### ISSUE TITLE
Allow post requests in `copyto` endpoint

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/CartoDB-SQL-API#587]
When we try to do a `copyto` with a lot of columns we get a `414 Client Error: Request-URI Too Large for url` error.

Could we consider adding `post` support for `copyto`?

Currently we allow `post` requests in `copyfrom` and `get` requests in `copyto` (this seems to be a decision based on the semantics of the HTTP request methods).

**Comment by rafatower** [comment]
This is supported since [v4.0.0](https://github.com/CartoDB/CartoDB-SQL-API/releases/tag/4.0.0) (Sep 30). I guess we can close this. Feel free to reopen if there's a bug.
