### ISSUE TITLE
bigint issue

### ISSUE THREAD

**Issue by oleurud** [CartoDB/CartoDB-SQL-API#604]
In Postgres, the bigint data type has a range from -9223372036854775808 to +9223372036854775807 (https://www.postgresql.org/docs/11/datatype-numeric.html)

If you do the following in psql:
```
CREATE TABLE bigint_text (text text, bigint bigint);

insert into bigint_text VALUES ('-9223372036854775808', -9223372036854775808), ('9223372036854775807', 9223372036854775807);
```

If you do `SELECT * FROM bigint_text;`:
```
         text         |        bigint        
----------------------+----------------------
 -9223372036854775808 | -9223372036854775808
 9223372036854775807  |  9223372036854775807
(2 rows)
```

But if you do the same querry using SQL API:
```
{
  "rows": [
    {
      "text": "-9223372036854775808",
      "bigint": -9223372036854776000
    },
    {
      "text": "9223372036854775807",
      "bigint": 9223372036854776000
    }
  ],
  "time": 0.001,
  "fields": {
    "text": {
      "type": "string",
      "pgtype": "text"
    },
    "bigint": {
      "type": "number",
      "pgtype": "int8"
    }
  },
  "total_rows": 2
}
```

The bigint values are "round" to `9223372036854776000`.

It seems to be a node.js problem with `JSON.parse`

**Comment by dgaubert** [comment]
cc/ @CartoDB/rt-managers

**Comment by rafatower** [comment]
This is not `JSON.parse` but a practical limitation in node implementation, which uses not integers but floats and they are rounded to ~ 2^53:

https://stackoverflow.com/questions/13502398/json-integers-limit-on-size

```
$ node 
> let a = 9223372036854775807
undefined
> a
9223372036854776000
```

I don't think this has an impact in practical terms, nor an easy fix. If you think otherwise, feel free to reopen.
